version: "3.8"
   
services:
    pgdb:
        image: postgres
        container_name: pgdb
        ports:
            - "5432:5432"
        volumes:
            - ./data:/var/lib/postgresql/data
        environment:
            - POSTGRES_DB=postgres
            - POSTGRES_USER=postgres
            - POSTGRES_PASSWORD=postgres
    erp:
        build: .
        container_name: erp
        volumes:
            - .:/usr/src/app
        command: python erp/runserver.py
        ports:
            - "8000:8000"
        depends_on:
            - pgdb
